theme = "ayu_mirage2"

[editor]
completion-timeout = 5
rulers = [100, 120]
bufferline = "multiple"
color-modes = true
text-width = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
goto-reference-include-declaration = false

[editor.smart-tab]
enable = false  # Smart my ass.

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "file-modification-indicator"]

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

esc = ["keep_primary_selection", "collapse_selection"]
tab = "buffer_picker"
H = ["extend_to_line_start"]
L = ["extend_to_line_end"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
