[[language]]
name = "c"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true

[[language]]
name = "cmake"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true

[[language]]
name = "cpp"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true

[[language]]
name = "javascript"
indent.tab-width = 4
indent.unit = "    "
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "dummy.js"] }
auto-format = true

[[language]]
name = "typescript"
indent.tab-width = 4
indent.unit = "    "
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "dummy.ts"] }
auto-format = true

[[language]]
name = "css"
indent.tab-width = 4
indent.unit = "    "
formatter = { command = "prettier", args = ["--parser", "css", "--stdin-filepath", "dummy.css"] }
auto-format = true

[[language]]
name = "html"
indent.tab-width = 4
indent.unit = "    "
formatter = { command = "prettier", args = ["--parser", "html", "--stdin-filepath", "dummy.html"] }
auto-format = true

[[language]]
name = "treehouse"
scope = "text.treehouse"
file-types = ["tree"]
indent.tab-width = 4
indent.unit = "    "
soft-wrap.enable = true
formatter = { command = "./target/debug/treehouse", args = ["fix", "-"] }

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.clangd.config]
args = ["--header-insertion=never"]
